export const RADIO_OPTIONS = [
  {
    label: 'Convert Video',
    value: 'convert-video',
    inputType: 'video',
    outputType: 'video',
    icon: 'video',
  },
  {
    label: 'Rescale Video',
    value: 'rescale-video',
    inputType: 'video',
    outputType: 'video',
    icon: 'video',
  },
  {
    label: 'Optimize Video for WhatsApp',
    value: 'optimize-video-whatsapp',
    inputType: 'video',
    outputType: 'video',
    icon: 'video',
  },
  {
    label: 'Convert Audio',
    value: 'convert-audio',
    inputType: 'audio',
    outputType: 'audio',
    icon: 'audio',
  },
  // {
  //   label: 'Convert Video to Audio',
  //   value: 'video-to-audio',
  //   inputType: 'video',
  //   outputType: 'audio',
  //   icon: 'audio',
  // },
  {
    label: 'Convert Video to GIF',
    value: 'video-to-gif',
    inputType: 'video',
    outputType: 'image',
    icon: 'image',
  },
  {
    label: 'Draw Waveform from Audio',
    value: 'audio-to-waveform',
    inputType: 'audio',
    outputType: 'image',
    icon: 'image',
  },
]
